# App configurations reference releases defined in releases.yaml.
# The release provides the chart source (repo, chart name, version).

[[helm]]
namespace = "cert-manager"
release = "cert-manager"
values = ["cert-manager/values.yaml"]
extra-resources = "cert-manager/extra"

[[helm]]
namespace = "surrealdb"
release = "surrealdb"
values = ["surrealdb/values.yaml"]

[[helm]]
namespace = "teleport-cluster"
release = "teleport-cluster"
values = ["teleport/cluster-values.yaml"]

[[helm]]
namespace = "teleport"
release = "teleport-kube-agent"
values = ["teleport/agent-values.yaml"]

[[website]]
name = "zq.lu"
namespace = "web"
hugo-repo = "https://github.com/nresare/zq.lu"

[[website]]
name = "noa.re"
namespace = "web"
hugo-repo = "https://github.com/nresare/noa.re"
extra-hostnames = "nadia.resare.com"

[[website]]
name = "id.noa.re"
namespace = "idelephant"
image = "nresare/idelephant:latest"
args = ["-c", "/config/idelephant.toml"]
external-secrets = [
    "/db-password",
    "/email-password",
]
[website.config]
"/config/idelephant.toml" = "idelephant/idelephant.toml"

[[simple]]
namespace = "acme-dns"
copy-from = "acme-dns/manifests"
[[simple.config]]
"/config/config.cfg" = "acme-dns/config.cfg"
